################################# Default configuration ###################
baseURL = "https://urumeaberri-elkartea.github.io"
title = "Urumea Berri G.K.E."
theme = "meghna-hugo"
DefaultContentLanguage = "es"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################




############################# Default Parameters ##########################
[params]
# logo = "images/logo.png"
# Meta data
description = "Urumea Berri Gastronomi Kultur Elkartea"
author = "Arkaitz"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = ""

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyARvwl-1isAy-EJGeiP0qFE-UDAQxWiKWU"
map_latitude = "43.277939"
map_longitude = "-1.954024"
map_marker = "images/marker.png"

############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#"


################################ Castellano ########################
[Languages.es]
languageName = "Castellano"
languageCode = "es-es"
contentDir = "content/castellano"
weight = 1
home = "Home"

[[Languages.es.menu.main]]
name = "Hazte socio/a"
URL = "socio"
weight = 2

[[Languages.es.menu.main]]
name = "El proyecto"
URL = "proyecto"
weight = 1

#[[Languages.es.menu.main]]
#name = "Cuantos somos"
#URL = "counter"
#weight = 3

[[Languages.es.menu.main]]
name = "Preguntas frequentes"
URL = "faq"
weight = 4

[[Languages.es.menu.main]]
name = "Noticias"
URL = "noticias"
weight = 5

[[Languages.es.menu.main]]
name = "Contacto"
URL = "contact"
weight = 6

################################ Euskera ########################
[Languages.eu]
languageName = "Euskara"
languageCode = "eu-ES"
contentDir = "content/euskera"
weight = 2
home = "Hasiera"

[[Languages.eu.menu.main]]
name = "Proiektua"
URL = "about"
weight = 1

[[Languages.eu.menu.main]]
name = "Zenbat gara"
URL = "services"
weight = 2

[[Languages.eu.menu.main]]
name = "Ohizko galderak"
URL = "team"
weight = 3

[[Languages.eu.menu.main]]
name = "Berriak"
URL = "blog"
weight = 4

[[Languages.eu.menu.main]]
name = "Kontaktua"
URL = "contact"
weight = 5
